---
name: Container Build

"on":
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: cargo_config
        run: |
          cargo vendor 1> ./cargo_config
      - name: Build
        uses: docker/build-push-action@v5
        with:
          platforms: "linux/amd64"
          tags: ghcr.io/${{ github.repository_owner }}/ldap-proxy:devel
          file: Dockerfile
          # Must use OCI exporter for multi-arch: https://github.com/docker/buildx/pull/1813
          outputs: type=oci,dest=/tmp/docker.tar
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: docker
      #     path: /tmp/docker.tar

  # push:
  #   name: Push Docker image
  #   # This step is split so that we don't apply "packages: write" permission
  #   # except when uploading the final Docker image to GHCR.
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main' && github.repository == "${{ github.repository_owner }}/ldap-proxy"
  #   needs: build
  #   permissions:
  #     packages: write

  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: docker
  #         path: /tmp

  #     # - name: Push image to GHCR
  #     #   run: |
  #     #     echo "${{ secrets.GITHUB_TOKEN }}" | oras login -u "${{ github.actor }}" --password-stdin ghcr.io
  #     #     oras copy --from-oci-layout "/tmp/docker.tar:devel" "ghcr.io/${{ github.repository_owner }}/ldap-proxy:devel"
